name: cpp-linter

on: [pull_request]

jobs:
    cpp-linter:
        name: cpp-linter
        runs-on: ubuntu-latest
        steps:
            - name: cpp-linter
              uses: shenxianpeng/cpp-linter-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
